# Generated by Django 4.0.5 on 2022-06-27 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0003_group_message_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Имя собеседника')),
            ],
            options={
                'verbose_name': 'Собеседник',
                'verbose_name_plural': 'Собеседники',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='messenger_app.person'),
        ),
    ]
