# Generated by Django 4.0.5 on 2022-06-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0004_person_message_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_id',
        ),
    ]
